AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Software-Dev-1 Serverless API deployment

Resources:
  SoftwareDevOneFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: server.handler
      Runtime: nodejs20.x
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
