apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: software-dev-1-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.software-dev-1.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: software-dev-1-service
            port:
              number: 80
